name: premium_notes
description: A premium glassmorphism notes application with 12 themes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  flutter_riverpod: ^2.4.9
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Fonts
  google_fonts: ^6.1.0
  
  # Date formatting
  intl: ^0.18.1
  
  # Icons
  lucide_icons: ^0.257.0
  
  # UI utilities
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^4.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.15.1

flutter:
  uses-material-design: true
