// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmRLbOBFhshcFmKmmmCCRUsQVwQ2iFCW4',
    appId: '1:62843359036:web:82aa269d0c9bc0e78d9839',
    messagingSenderId: '62843359036',
    projectId: 'glasswave-4f5da',
    authDomain: 'glasswave-4f5da.firebaseapp.com',
    storageBucket: 'glasswave-4f5da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHQID-TUZJNt6uRZu9L0C8y7xmsJyuLRs',
    appId: '1:62843359036:android:4b670117f4c9819e8d9839',
    messagingSenderId: '62843359036',
    projectId: 'glasswave-4f5da',
    storageBucket: 'glasswave-4f5da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgLav3Gctl3kXATTXW7hB1PSc3ktYJe-A',
    appId: '1:62843359036:ios:172f2fc935706e2e8d9839',
    messagingSenderId: '62843359036',
    projectId: 'glasswave-4f5da',
    storageBucket: 'glasswave-4f5da.firebasestorage.app',
    iosBundleId: 'com.almaz.glasswave',
  );
}
