name: Deploy Flutter Web to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: 
   contents: read
   deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: glasswave # You can change this to your desired project name
          directory: build/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
